FROM java:8-alpine
MAINTAINER Your Name <you@example.com>

ADD target/uberjar/e02-introduction-to-luminus_lambwiki.jar /e02-introduction-to-luminus_lambwiki/app.jar

EXPOSE 3000

CMD ["java", "-jar", "/e02-introduction-to-luminus_lambwiki/app.jar"]
